-- shared/colors.lua
SPZ_Tuners = SPZ_Tuners or {}

-- Predefined GTA V Vehicle Primary/Secondary Color Palette
SPZ_Tuners.Colors = {
    { label = "Metallic Black", index = 0 },
    { label = "Metallic Graphite", index = 1 },
    { label = "Metallic Black Steel", index = 2 },
    { label = "Metallic Dark Silver", index = 3 },
    { label = "Metallic Silver", index = 4 },
    { label = "Metallic Blue Silver", index = 5 },
    { label = "Metallic Steel Gray", index = 6 },
    { label = "Metallic Shadow Silver", index = 7 },
    { label = "Metallic Stone Silver", index = 8 },
    { label = "Metallic Midnight Silver", index = 9 },
    { label = "Metallic Gun Metal", index = 10 },
    { label = "Metallic Red", index = 27 },
    { label = "Metallic Torino Red", index = 28 },
    { label = "Metallic Formula Red", index = 29 },
    { label = "Metallic Blaze Red", index = 30 },
    { label = "Metallic Grace Red", index = 31 },
    { label = "Metallic Garnet Red", index = 32 },
    { label = "Metallic Sunset Red", index = 33 },
    { label = "Metallic Cabernet Red", index = 34 },
    { label = "Metallic Candy Red", index = 35 },
    { label = "Metallic Dark Blue", index = 61 },
    { label = "Metallic Saxon Blue", index = 62 },
    { label = "Metallic Blue", index = 63 },
    { label = "Metallic Mariner Blue", index = 64 },
    { label = "Metallic Harbor Blue", index = 65 },
    { label = "Metallic Diamond Blue", index = 67 },
    { label = "Metallic Surf Blue", index = 68 },
    { label = "Metallic Nautical Blue", index = 69 },
    { label = "Metallic Racing Blue", index = 73 },
    { label = "Metallic Lime Green", index = 55 },
    { label = "Metallic Green", index = 50 },
    { label = "Metallic Olive Green", index = 51 },
    { label = "Metallic Yellow", index = 88 },
    { label = "Metallic Race Yellow", index = 89 },
    { label = "Metallic Gold", index = 99 },
    { label = "Metallic Orange", index = 41 },
    { label = "Metallic Bright Orange", index = 138 },
    { label = "Matte Black", index = 12 },
    { label = "Matte Gray", index = 13 },
    { label = "Matte Light Gray", index = 14 },
    { label = "Matte White", index = 131 },
    { label = "Matte Red", index = 39 },
    { label = "Matte Dark Red", index = 40 },
    { label = "Matte Orange", index = 42 },
    { label = "Matte Yellow", index = 89 },
    { label = "Matte Lime Green", index = 55 },
    { label = "Matte Midnight Blue", index = 82 },
    { label = "Matte Blue", index = 83 },
    { label = "Matte Purple", index = 148 },
    { label = "Chrome", index = 120 },
    { label = "Brushed Steel", index = 117 },
    { label = "Brushed Black Steel", index = 118 },
    { label = "Brushed Aluminum", index = 119 },
    { label = "Pure Gold", index = 158 },
    { label = "Brushed Gold", index = 159 },
}

-- Chameleon paints. 161-222 are in the base game from build 2944 (this server
-- enforces 3407). 223-242, the Fubuki-jo specials, are added by
-- data/carcols_gen9.meta + data/carmodcols_gen9.meta and painted with
-- stream/vehicle_paint_ramps.ytd. Those metas used to sit in stream/, where
-- FiveM never loads a .meta, so the specials never existed; they are now
-- registered with data_file in fxmanifest.lua.
SPZ_Tuners.ChameleonColors = {
    { label = "Anodized Red Pearl", index = 161 },
    { label = "Anodized Wine Pearl", index = 162 },
    { label = "Anodized Purple Pearl", index = 163 },
    { label = "Anodized Blue Pearl", index = 164 },
    { label = "Anodized Green Pearl", index = 165 },
    { label = "Anodized Lime Pearl", index = 166 },
    { label = "Anodized Copper Pearl", index = 167 },
    { label = "Anodized Bronze Pearl", index = 168 },
    { label = "Anodized Champagne Pearl", index = 169 },
    { label = "Anodized Gold Pearl", index = 170 },
    { label = "Green/Blue Flip", index = 171 },
    { label = "Green/Red Flip", index = 172 },
    { label = "Green/Brown Flip", index = 173 },
    { label = "Green/Turquoise Flip", index = 174 },
    { label = "Green/Purple Flip", index = 175 },
    { label = "Teal/Purple Flip", index = 176 },
    { label = "Turquoise/Red Flip", index = 177 },
    { label = "Turquoise/Purple Flip", index = 178 },
    { label = "Cyan/Purple Flip", index = 179 },
    { label = "Blue/Pink Flip", index = 180 },
    { label = "Blue/Green Flip", index = 181 },
    { label = "Purple/Red Flip", index = 182 },
    { label = "Purple/Green Flip", index = 183 },
    { label = "Magenta/Green Flip", index = 184 },
    { label = "Magenta/Yellow Flip", index = 185 },
    { label = "Burgundy/Green Flip", index = 186 },
    { label = "Magenta/Cyan Flip", index = 187 },
    { label = "Copper/Purple Flip", index = 188 },
    { label = "Magenta/Orange Flip", index = 189 },
    { label = "Red/Orange Flip", index = 190 },
    { label = "Orange/Purple Flip", index = 191 },
    { label = "Orange/Blue Flip", index = 192 },
    { label = "White/Purple Flip", index = 193 },
    { label = "Red/Rainbow Flip", index = 194 },
    { label = "Blue/Rainbow Flip", index = 195 },
    { label = "Dark Green Pearl", index = 196 },
    { label = "Dark Teal Pearl", index = 197 },
    { label = "Dark Blue Pearl", index = 198 },
    { label = "Dark Purple Pearl", index = 199 },
    { label = "Oil Slick Pearl", index = 200 },
    { label = "Light Green Pearl", index = 201 },
    { label = "Light Blue Pearl", index = 202 },
    { label = "Light Purple Pearl", index = 203 },
    { label = "Light Pink Pearl", index = 204 },
    { label = "Off White Pearl", index = 205 },
    { label = "Cute Pink Pearl", index = 206 },
    { label = "Baby Yellow Pearl", index = 207 },
    { label = "Baby Green Pearl", index = 208 },
    { label = "Baby Blue Pearl", index = 209 },
    { label = "Cream Pearl", index = 210 },
    { label = "White Prismatic Pearl", index = 211 },
    { label = "Graphite Prismatic Pearl", index = 212 },
    { label = "Blue Prismatic Pearl", index = 213 },
    { label = "Purple Prismatic Pearl", index = 214 },
    { label = "Hot Pink Prismatic Pearl", index = 215 },
    { label = "Red Prismatic Pearl", index = 216 },
    { label = "Green Prismatic Pearl", index = 217 },
    { label = "Black Prismatic Pearl", index = 218 },
    { label = "Oil Spill Prismatic Pearl", index = 219 },
    { label = "Rainbow Prismatic Pearl", index = 220 },
    { label = "Black Holographic Pearl", index = 221 },
    { label = "White Holographic Pearl", index = 222 },
    { label = "Fubuki-jo Specials: Monochrome", index = 223 },
    { label = "Fubuki-jo Specials: Night & Day", index = 224 },
    { label = "Fubuki-jo Specials: The Verlierer", index = 225 },
    { label = "Fubuki-jo Specials: Sprunk Extreme", index = 226 },
    { label = "Fubuki-jo Specials: Vice City", index = 227 },
    { label = "Fubuki-jo Specials: Synthwave Night", index = 228 },
    { label = "Fubuki-jo Specials: Four Seasons", index = 229 },
    { label = "Fubuki-jo Specials: M9 Throwback", index = 230 },
    { label = "Fubuki-jo Specials: Bubblegum", index = 231 },
    { label = "Fubuki-jo Specials: Full Rainbow", index = 232 },
    { label = "Fubuki-jo Specials: Sunset", index = 233 },
    { label = "Fubuki-jo Specials: The Seven", index = 234 },
    { label = "Fubuki-jo Specials: Kamen Rider", index = 235 },
    { label = "Fubuki-jo Specials: Chromatic", index = 236 },
    { label = "Fubuki-jo Specials: It's Christmas!", index = 237 },
    { label = "Fubuki-jo Specials: Temperature", index = 238 },
    { label = "Fubuki-jo Specials: HSW Badge", index = 239 },
    { label = "Fubuki-jo Specials: Anod. Lightning", index = 240 },
    { label = "Fubuki-jo Specials: Emeralds", index = 241 },
    { label = "Fubuki-jo Specials: Fubuki Castle", index = 242 },
}

function SPZ_Tuners.GetChameleonColors()
    if GetGameBuildNumber() < 2944 then return {} end
    return SPZ_Tuners.ChameleonColors
end

-- Xenon Headlight Colors (GTA V Xenon Light Index: 0 to 12)
SPZ_Tuners.XenonColors = {
    { label = "Default White", index = -1 },
    { label = "White", index = 0 },
    { label = "Blue", index = 1 },
    { label = "Electric Blue", index = 2 },
    { label = "Mint Green", index = 3 },
    { label = "Lime Green", index = 4 },
    { label = "Yellow", index = 5 },
    { label = "Golden Shower", index = 6 },
    { label = "Orange", index = 7 },
    { label = "Red", index = 8 },
    { label = "Pony Pink", index = 9 },
    { label = "Hot Pink", index = 10 },
    { label = "Purple", index = 11 },
    { label = "Blacklight", index = 12 },
}

-- Predefined Neon Colors RGB
SPZ_Tuners.NeonColors = {
    { label = "White", rgb = { 255, 255, 255 } },
    { label = "Blue", rgb = { 2, 21, 255 } },
    { label = "Electric Blue", rgb = { 3, 83, 255 } },
    { label = "Mint Green", rgb = { 0, 255, 140 } },
    { label = "Lime Green", rgb = { 15, 255, 0 } },
    { label = "Yellow", rgb = { 255, 255, 0 } },
    { label = "Golden Orange", rgb = { 255, 150, 0 } },
    { label = "Orange", rgb = { 255, 62, 0 } },
    { label = "Red", rgb = { 255, 1, 1 } },
    { label = "Pony Pink", rgb = { 255, 50, 100 } },
    { label = "Hot Pink", rgb = { 255, 5, 190 } },
    { label = "Purple", rgb = { 35, 1, 255 } },
    { label = "Blacklight", rgb = { 15, 3, 255 } },
}

-- Window Tints
SPZ_Tuners.WindowTints = {
    { label = "Stock / None", index = 0 },
    { label = "Pure Black", index = 1 },
    { label = "Dark Smoke", index = 2 },
    { label = "Light Smoke", index = 3 },
    { label = "Limo", index = 4 },
    { label = "Green Tint", index = 5 },
}

-- License Plate Styles
SPZ_Tuners.PlateStyles = {
    { label = "Blue on White 1", index = 0 },
    { label = "Yellow on Black", index = 1 },
    { label = "Yellow on Blue", index = 2 },
    { label = "Blue on White 2", index = 3 },
    { label = "Blue on White 3", index = 4 },
    { label = "Yankton Special", index = 5 },
}

-- Wheel Category Types
SPZ_Tuners.WheelTypes = {
    { label = "Sport", type = 0 },
    { label = "Muscle", type = 1 },
    { label = "Lowrider", type = 2 },
    { label = "SUV", type = 3 },
    { label = "Offroad", type = 4 },
    { label = "Tuner", type = 5 },
    { label = "Bike Wheels", type = 6 },
    { label = "High End", type = 7 },
    { label = "Benny's Original", type = 8 },
    { label = "Benny's Bespoke", type = 9 },
    { label = "Open Wheel", type = 10 },
    { label = "Street", type = 11 },
    { label = "Track", type = 12 },
}
